language: php
php:
  - 7.4

os: linux
dist: xenial

jobs:
  include:
    - php: 7.4
      env: DB=MYSQL CORE_RELEASE=4.7
      services:
        - mysql
    - php: 7.3
      env: DB=PGSQL CORE_RELEASE=4.6
      services:
        - postgresql
    - php: 7.2
      env: DB=MYSQL CORE_RELEASE=4.6
      services:
        - mysql

before_script:
  - composer self-update || true
  - composer validate
  - composer require --no-update silverstripe/recipe-cms:"^$CORE_RELEASE" --prefer-dist
  - composer require --no-update phpunit/phpunit:^5.7 --prefer-dist
  - if [[ $DB == PGSQL ]]; then composer require silverstripe/postgresql:~2.0 --prefer-dist --no-update; fi
  - composer install --prefer-dist --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose

script:
  - vendor/bin/phpunit
