mappings:
  AdvancedWidgetEditorInterface: UndefinedOffset\AdvancedWidgetEditor\Extensions\AdvancedWidgetEditorInterface
  AdvancedWidgetPageExtension: UndefinedOffset\AdvancedWidgetEditor\Extensions\AdvancedWidgetPageExtension
  AdvancedWidgetAreaEditor: UndefinedOffset\AdvancedWidgetEditor\Forms\AdvancedWidgetAreaEditor
  AdvancedWidgetsHasManyList: UndefinedOffset\AdvancedWidgetEditor\Model\AdvancedWidgetsHasManyList
  AdvancedWidgetFormShiv: UndefinedOffset\AdvancedWidgetEditor\Object\AdvancedWidgetFormShiv
  AdvancedWidgetEditorTest: UndefinedOffset\AdvancedWidgetEditor\Tests\AdvancedWidgetEditorTest
  AdvancedWidgetEditorTest_FakePage: UndefinedOffset\AdvancedWidgetEditor\Tests\AdvancedWidgetEditorTest_FakePage
  AdvancedWidgetEditorTest_TestWidget: UndefinedOffset\AdvancedWidgetEditor\Tests\AdvancedWidgetEditorTest_TestWidget
  AdvancedWidgetEditorTest_TestObject: UndefinedOffset\AdvancedWidgetEditor\Tests\AdvancedWidgetEditorTest_TestObject
  AdvancedWidgetEditor_TestController: UndefinedOffset\AdvancedWidgetEditor\Tests\AdvancedWidgetEditor_TestController
