---
Name: advancedwidgeteditor
After: 'cms/*', 'framework/*', 'widgets/*'
---
SilverStripe\Widgets\Model\Widget:
  extensions:
    - UndefinedOffset\AdvancedWidgetEditor\Extensions\AdvancedWidgetEditorInterface
