---
Name: advancedwidgeteditor
After: "silverstripe/widgets#*"
---
SilverStripe\Widgets\Model\Widget:
  extensions:
    - 'UndefinedOffset\AdvancedWidgetEditor\Extensions\AdvancedWidgetEditorInterface'
